name: run_guo_et_al_reprod
dataset: tus-rec
num_dataloader_workers: 8
logger: wandb
seed: 0
batch_size: 50
epochs: 4000
device: cuda
use_bfloat: false
use_amp: false
scheduler: cosine
clip_grad: 3
optimizer: adam
lr: 0.0001
weight_decay: 0
model_weights: null
debug: false
window_size: 5
resize_to: null
tus_rec_crop: true
use_corr_loss: false
model: guo_et_al
inference_batch_size: 8
check_val_every_n_epoch: 50