# Second step of training the winning TUS-REC 2025 model. 
# This thaws the CNN backbone and trains it alongside the transformer modules to slightly improve error compared to stage 2.
# This should achieve minimum ddf/5pt-avg_global_displacement_error/val-tus-rec-2025-val 9.01144mm

model:
  name: dualtrack_fusion_model
  global_encoder_cfg:
    name: global_encoder_cnn
    max_position_embeddings: 4096
    max_seq_length: 4096
    features_only: true
  local_encoder_cfg:
    name: dualtrack_loc_enc_stg3_legacy
    backbone_cfg:
      max_subsequence_size: 512
    max_position_embeddings: 4096
    freeze_backbone: false
    keep_backbone_in_eval_mode: true
    features_only: true
  max_position_embeddings: 4096
  load_kw:
    strict: false
    handle_size_mismatch: true
  
  # ==========================
  # point to the best checkpoint of the finetuned dualtrack produced by stg1.yaml
  checkpoint: "???" # e.g., experiments/2025-Aug-28/8:09.20PM/checkpoint/best.pt
  # ==========================

model_input_keymap:
  global_encoder_inputs: global_encoder_images
  local_encoder_inputs: local_encoder_images

data:
  version: custom
  dataset: tus-rec-2025-full-train
  val_dataset_name:
    val-tus-rec-2025-val: tus-rec-2025-val
  num_dataloader_workers: 8
  batch_size: 1
  sequence_length_train: null
  transform_kwargs:
    transform_version: fusion
    random_reverse_sweep: true
    random_subsample_sequence: true
    random_horizontal_flip: true
    random_crop: true
    global_encoder_preprocessing_kw:
      in_channels: 1
      mean:
      - 0
      std:
      - 1
      resize_to:
      - 224
      - 224
    local_encoder_preprocessing_kw:
      resize_to: null
    load_preprocessed_images_from_disk: true
  dataset_kwargs:
    mode: h5_dynamic_load
  persistent_workers: true
  sequence_keys:
  - images
  - images_downsampled-224
  - tracking
  no_distributed_val_sampler: true

train:
  lr: 1.0e-04
  epochs: 200
  warmup_epochs: 1
  weight_decay: 0
  val_every: 1

seed: 0
device: cuda
use_amp: true
logger: wandb
logger_kw:
  wandb_project: dualtrack
evaluator_kw:
  include_images: true
debug: false
do_distributed_training: true
slurm:
  nodes: 1
  mem_gb: 490
  tasks_per_node: 4
  slurm_gres: gpu:4
  timeout_min: 480
  slurm_exclude: kn068
  
tracked_metric: ddf/5pt-avg_global_displacement_error/val-tus-rec-2025-val
