model: 
  name: dualtrack_fusion_model
  global_encoder_cfg: 
    name: global_encoder_cnn
    max_position_embeddings: 4096
    max_seq_length: 4096
  local_encoder_cfg: 
    name: dualtrack_loc_enc_stg3_legacy
    backbone_cfg:
      max_subsequence_size: 1024
    max_position_embeddings: 4096
    freeze_backbone: true
    use_cache: true
  max_position_embeddings: 4096
  load_kw: 
    strict: false
    handle_size_mismatch: true
  checkpoint: data/checkpoints/dualtrack_ft.pt

data: 
  dataset: tus-rec-2025
  num_workers: 8
  global_encoder_preprocessing_kw:  
    in_channels: 1
    mean: [0] 
    std: [1]
    resize_to: [224, 224]
  local_encoder_preprocessing_kw: 
    resize_to: [256, 256]
  use_augmentations: true
  load_preprocessed_images_from_disk: true
  batch_size: ${train.batch_size}
  features_paths: {}
  subsequence_length_train: null

train: 
  lr: 0.0001
  epochs: 100
  warmup_epochs: 1
  weight_decay: 0.0
  val_every: 1
  batch_size: 1

seed: 0
device: cuda
use_amp: true

logger: wandb
logger_kw: 
  wandb_project: dualtrack
  log_level: 20 # 10 for debug
evaluator_kw:   
  include_images: true

debug: false
resume: true

