model:
  name: global_encoder_medsam

data:
  version: global_encoder
  dataset: tus-rec
  use_augmentations: true
  mean: [0, 0, 0]
  std: [1, 1, 1]
  in_channels: 3
  batch_size: 4

train:
  lr: 0.0001
  epochs: 5000
  warmup_epochs: 0
  weight_decay: 0.001
  batch_size: 16
  val_every: 100

seed: 0
device: cuda
use_amp: true

logger: wandb
logger_kw:
  wandb_project: dualtrack
evaluator_kw:
  include_images: true

debug: false
resume: false